TE-4494 Added additional BC check for enabling mapping resources in t…
spryker/synchronization-behavior pull request #18
Opened 2019-12-30 15:50 UTC by SArtemV

- Developer(s): @asaulenko 

- Peer Reviewer:

- Ticket: https://spryker.atlassian.net/browse/TE-4494

- Academy PR: ACADEMY_URL_HERE

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department
- [ ] All new or heavily changed classes get an "A" rating (Scrutinizer), except Facades, Factories, QueryContainers and Tests

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SynchronizationBehavior  | patch          |                       |

#### Release Notes

This release updated the synchronization module to the latest version.

-----------------------------------------

#### Module SynchronizationBehavior

_**Patch:** Backwards-compatible bug fix_

Def of done (by responsible developer):
- [ ] All changes are backward-compatible. Outdated code is marked as deprecated.
- [ ] The change is isolated and not mixed with any cleanups or other changes.
- [ ] New and changed facade methods covered by functional tests. / Has nothing to test.
- [ ] New and changed complex business logic is covered by unit or integration tests. / Has nothing to test.

##### Change log

Improvements

- Added additional BC check for enabling mapping resources in the legacy environment

2020-01-03 08:40 UTC, lockw1n approved these changes

2020-01-03 08:53 UTC, nuzzy approved these changes

2020-01-03 13:33 UTC, gechetspr requested changes
Small thing to fix. Also please add a RG and BC check branch.

2020-01-03 13:33 UTC, gechetspr commented on src/Spryker/Zed/SynchronizationBehavior/Persistence/Propel/Behavior/SynchronizationBehavior.php
> +         * @deprecated Will be removed without replacement.
I think we don't need deprecation messages inside the method body. The check method is deprecated already

2020-01-09 12:07 UTC, alexanderM91 approved these changes

2020-01-09 12:56 UTC, dereuromark commented on src/Spryker/Zed/SynchronizationBehavior/Persistence/Propel/Behavior/SynchronizationBehavior.php
> +
whitespace noise

2020-01-09 15:43 UTC, ZakirovDamir commented on src/Spryker/Zed/SynchronizationBehavior/Persistence/Propel/Behavior/SynchronizationBehavior.php
> +
Removed

2020-01-10 09:02 UTC, gechetspr approved these changes

2020-01-10 09:04 UTC, merged