TE-8219 / TE-8220 configuration for data field type
spryker/synchronization-behavior pull request #28
Opened 2020-12-15 09:06 UTC by Nidhognit

- Developer(s): @Nidhognit

- Ticket: https://spryker.atlassian.net/browse/TE-8219

- Release Group: URL_HERE

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SynchronizationBehavior  | patch                 |                       |

-----------------------------------------

#### Module SynchronizationBehavior

##### Change log

Fixes

Adjusted default column type for "data" field, now it's Propel "CLOB" type.
For PostgreSQL thats mean no changes.
For MariaDB field type changed from TEXT to LONGTEXT.

2020-12-15 10:13 UTC, gechetspr requested changes
Also changelogs and release type need to be adjusted.

This is definitely not a patch release.

Changelogs should be in the form of list
Also please check https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs to get some examples

2020-12-15 10:13 UTC, gechetspr commented on src/Spryker/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
> +     * - Returns the the Propel type for "data" column.
```suggestion
     * - Returns the Propel's type for `data` column.
```

2020-12-15 10:15 UTC, dereuromark commented on src/Spryker/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
> +     * - Returns the the Propel type for "data" column.
without "the"

2020-12-15 10:20 UTC, bezpiatovs approved these changes
except @gechetspr comments the rest is looking good

2020-12-17 11:59 UTC, gechetspr approved these changes

2020-12-17 16:00 UTC, asaulenko approved these changes

2020-12-21 14:31 UTC, merged