Multistore publish synchronize
spryker/synchronization-behavior pull request #3
Opened 2018-03-06 10:10 UTC by gerner-spryker

- Developer(s): @gerner-spryker, @ehsanmx 

- Peer Reviewer: @ehsanmx 

- Ticket: https://spryker.atlassian.net/browse/CORE-2793
- Ticket: https://spryker.atlassian.net/browse/CORE-2977 

- Core PR: TBD

- Release Overview: -

#### Please confirm

- [x] No new OS components - or they have been approved by legal department
- [x] All new or heavily changed classes get an "A" rating (Scrutinizer), except Facades, Factories, QueryContainers and Tests

#### Documentation

- [x] Functional documentation provided or in progress?
- [x] Integration guide for projects provided or not needed?
- [x] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SynchronizationBehavior              | minor                |                      |

#### Release Notes

Entity related change (save/delete) emitted synchronisation messages can target different pools based on either "Store" or a pre defined queue pool.

-----------------------------------------

#### Module SynchronizationBehavior

_**Minor:** Added functionality in a backwards-compatible manner_

Def of done (by responsible developer):
- [x] All changes are backward-compatible. Outdated code is marked as deprecated.
- [x] New code fits to the architecture rules.
- [x] All new or changed business logic is covered by functional tests (in Zed business layer).

##### Change log

Improvements

- Adding and updating missing module requirements in composer.json.
- The generated `sendToQueue()` methods in propel models with the synchronization behavior will also add the Store value to the message or the pool name if any of them is defined.

2018-03-14 15:23 UTC, a-sabaa approved these changes

2018-03-16 10:36 UTC, aurisl requested changes

2018-03-16 10:36 UTC, aurisl commented on src/Spryker/Zed/SynchronizationBehavior/Persistence/Propel/Behavior/SynchronizationBehavior.php
>      protected function addSendToQueueMethod()
What if `$queuePoolName` and `$hasStore `  is empty. This could happen right?

2018-03-16 10:36 UTC, aurisl commented on src/Spryker/Zed/SynchronizationBehavior/Persistence/Propel/Behavior/SynchronizationBehavior.php
> +    protected function getQueuePoolName()
usually get must return value.

2018-05-23 14:07 UTC, ehsanmx commented
This will be merged with PR https://github.com/spryker/synchronization-behavior/pull/4

2018-05-23 14:07 UTC, closed without merging